---
name: lint
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
  pull_request: {}

jobs:

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - run: composer install
      - run: ./vendor/bin/php-cs-fixer fix --dry-run

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8,2
      - run: composer install
      - run: ./vendor/bin/phpstan